nhnacademy-be4-ckin/ckin-api

- src/main/java/store/ckin/api/member/controller/MemberController.java
- src/main/java/store/ckin/api/member/domain/MemberInfoDetailResponseDto.java
- src/main/java/store/ckin/api/member/exception/MemberNotFoundException.java
- src/main/java/store/ckin/api/member/repository/MemberRepositoryCustom.java
- src/main/java/store/ckin/api/member/repository/impl/MemberRepositoryImpl.java
- src/main/java/store/ckin/api/member/service/MemberService.java
- src/main/java/store/ckin/api/member/service/impl/MemberServiceImpl.java
- SecurityContextHolder 에 넣을 인증된 멤버의 정보 요청 처리하는 것을 추가 하였습니다.
>
> [FEAT] getMemberInfoDetail

- src/test/java/store/ckin/api/member/controller/MemberControllerTest.java
- src/test/java/store/ckin/api/member/repository/MemberRepositoryTest.java
- src/test/java/store/ckin/api/member/service/impl/MemberServiceImplTest.java
> [REFACTOR] Member Entity 관련 Test 수정

- src/main/java/store/ckin/api/booksale/service/impl/BookSaleServiceImpl.java
- src/main/java/store/ckin/api/packaging/service/impl/PackagingServiceImpl.java
- src/main/java/store/ckin/api/sale/dto/request/SaleCreateRequestDto.java
- src/main/java/store/ckin/api/sale/dto/response/SaleWithBookResponseDto.java
- src/main/java/store/ckin/api/sale/repository/SaleRepositoryImpl.java
사용 안하는 어노테이션(`@Slf4j`)와 주문자 이름과 연락처 필드명 수정하였습니다.
> [REFACTOR] 코드 수정

- src/main/java/store/ckin/api/grade/entity/Grade.java
- src/main/java/store/ckin/api/member/controller/MemberController.java
- src/main/java/store/ckin/api/member/domain/request/MemberAuthRequestDto.java
- src/main/java/store/ckin/api/member/domain/request/MemberCreateRequestDto.java
- src/main/java/store/ckin/api/member/domain/response/MemberAuthResponseDto.java
- src/main/java/store/ckin/api/member/domain/response/MemberInfoDetailResponseDto.java
- src/main/java/store/ckin/api/member/domain/response/MemberMyPageResponseDto.java
- src/main/java/store/ckin/api/member/repository/MemberRepositoryCustom.java
- src/main/java/store/ckin/api/member/repository/impl/MemberRepositoryImpl.java
- src/main/java/store/ckin/api/member/service/MemberService.java
- src/main/java/store/ckin/api/member/service/impl/MemberServiceImpl.java
- src/test/java/store/ckin/api/member/controller/MemberControllerTest.java
- src/test/java/store/ckin/api/member/service/impl/MemberServiceImplTest.java
> [FEAT] 마이 페이지 View 조회 REST API

- src/main/java/store/ckin/api/ApiApplication.java
- src/main/java/store/ckin/api/author/controller/AuthorController.java
- src/main/java/store/ckin/api/author/repository/AuthorRepositoryCustom.java
- src/main/java/store/ckin/api/author/repository/impl/AuthorRepositoryImpl.java
- src/main/java/store/ckin/api/book/repository/BookRepositoryCustom.java
> [REFACTOR] code smell 제거

- src/main/java/store/ckin/api/book/controller/BookController.java
- src/main/java/store/ckin/api/book/service/BookService.java
- src/main/java/store/ckin/api/book/service/impl/BookServiceImpl.java
> 도서 Id List로 카테고리 Id List 조회하는 기능 추가했습니다.
> [FEATURE] 도서 Id List로 카테고리 Id List 조회

- src/main/java/store/ckin/api/book/dto/response/BookExtractionResponseDto.java
- src/main/java/store/ckin/api/book/entity/Book.java
- src/main/java/store/ckin/api/book/repository/impl/BookRepositoryImpl.java
- src/main/java/store/ckin/api/booksale/dto/response/BookSaleResponseDto.java
- src/main/java/store/ckin/api/booksale/entity/BookSale.java
- src/main/java/store/ckin/api/sale/controller/SaleController.java
- src/main/java/store/ckin/api/sale/dto/response/SaleInfoResponseDto.java
- src/main/java/store/ckin/api/sale/dto/response/SaleWithBookResponseDto.java
- src/main/java/store/ckin/api/sale/exception/SaleNumberNotFoundException.java
- src/main/java/store/ckin/api/sale/facade/SaleFacade.java
- src/main/java/store/ckin/api/sale/repository/SaleRepository.java
- src/main/java/store/ckin/api/sale/repository/SaleRepositoryCustom.java
- src/main/java/store/ckin/api/sale/repository/SaleRepositoryImpl.java
- src/main/java/store/ckin/api/sale/service/SaleService.java
- src/main/java/store/ckin/api/sale/service/impl/SaleServiceImpl.java
- src/test/java/store/ckin/api/sale/controller/SaleControllerTest.java
- src/test/java/store/ckin/api/sale/facade/SaleFacadeTest.java
- src/test/java/store/ckin/api/sale/repository/SaleRepositoryTest.java
- src/test/java/store/ckin/api/sale/service/impl/SaleServiceImplTest.java
DB에 저장된 File URL을 가져와 해당 URL을 보여주는 방식으로 변경하였습니다.
> [FEAT] 주문 - 썸네일 파일 불러오기

- src/main/java/store/ckin/api/author/controller/AuthorController.java
- src/main/java/store/ckin/api/author/exception/AuthorNotFoundException.java
- src/main/java/store/ckin/api/author/repository/AuthorRepositoryCustom.java
- src/main/java/store/ckin/api/author/repository/impl/AuthorRepositoryImpl.java
- src/main/java/store/ckin/api/author/service/AuthorService.java
- src/main/java/store/ckin/api/author/service/impl/AuthorServiceImpl.java
- src/main/java/store/ckin/api/book/controller/BookController.java
- src/main/java/store/ckin/api/book/repository/BookRepositoryCustom.java
- src/main/java/store/ckin/api/book/repository/impl/BookRepositoryImpl.java
- src/main/java/store/ckin/api/book/service/BookService.java
- src/main/java/store/ckin/api/book/service/impl/BookServiceImpl.java
- src/main/java/store/ckin/api/category/controller/CategoryController.java
- src/main/java/store/ckin/api/category/repository/CategoryRepository.java
- src/main/java/store/ckin/api/category/service/CategoryService.java
- src/main/java/store/ckin/api/category/service/impl/CategoryServiceImpl.java
- src/main/java/store/ckin/api/objectstorage/service/impl/ObjectStorageServiceImpl.java
>[#85](https://github.com/nhnacademy-be4-ckin/ckin-front/issues/85)
> 썸네일 수정 기능 및 사진 등록 시 ObjectStorage에 제목 빼고 저장
> 썸네일 수정하면 기존의 ObjectStorage에 있던 사진 제거는 추후 구현하겠습니다!
>
> [FEATURE] 썸네일 수정 기능 및 사진 등록 시 ObjectStorage에 제목 빼고 저장

- src/main/java/store/ckin/api/booksale/service/impl/BookSaleServiceImpl.java
- src/main/java/store/ckin/api/sale/service/impl/SaleServiceImpl.java
배포서버에서 오류나는 주문 생성 부분에서
BookSale을 생성할 때 Book, Sale Entity를 넣어주지 않아 오류가 나는 것을 수정했습니다.
> [FIX] BookSale Save 오류 수정

- src/main/java/store/ckin/api/booksale/service/impl/BookSaleServiceImpl.java
- src/test/java/store/ckin/api/booksale/repository/BookSaleRepositoryTest.java
- src/test/java/store/ckin/api/booksale/service/impl/BookSaleServiceImplTest.java
- src/test/java/store/ckin/api/payment/service/impl/PaymentServiceImplTest.java
> [FIX] 테스트 코드 수정

- src/main/java/store/ckin/api/booksale/service/impl/BookSaleServiceImpl.java
- src/main/java/store/ckin/api/sale/service/impl/SaleServiceImpl.java
- src/test/java/store/ckin/api/booksale/repository/BookSaleRepositoryTest.java
- src/test/java/store/ckin/api/booksale/service/impl/BookSaleServiceImplTest.java
- src/test/java/store/ckin/api/payment/service/impl/PaymentServiceImplTest.java
#108 #110 
BookSale에 관련된 테스트코드 수정 후 다시 배포합니다.
> [DEPLOY] 테스트 코드 수정 후 배포

- src/main/java/store/ckin/api/member/controller/MemberController.java
> [FIX] 마이페이지 오류 로그 확인

- src/main/java/store/ckin/api/sale/controller/SaleController.java
- src/main/java/store/ckin/api/sale/exception/SaleNotFoundExceptionBySaleNumber.java
- src/main/java/store/ckin/api/sale/facade/SaleFacade.java
- src/main/java/store/ckin/api/sale/repository/SaleRepositoryCustom.java
- src/main/java/store/ckin/api/sale/repository/SaleRepositoryImpl.java
- src/main/java/store/ckin/api/sale/service/SaleService.java
- src/main/java/store/ckin/api/sale/service/impl/SaleServiceImpl.java
- src/test/java/store/ckin/api/sale/controller/SaleControllerTest.java
- src/test/java/store/ckin/api/sale/facade/SaleFacadeTest.java
- src/test/java/store/ckin/api/sale/repository/SaleRepositoryTest.java
- src/test/java/store/ckin/api/sale/service/impl/SaleServiceImplTest.java
프론트에서 RedirectAttributes를 사용하지 않는 방식으로 변경 후 API 서버 수정
> [FEAT] 주문 - 프론트 수정에 따른 수정

- src/main/java/store/ckin/api/book/entity/Book.java
#87 
elastic search 에서 수정된 데이터를 갱신해주기 위하여 필드를 추가하였습니다
> [UPDATE] modification_time 필드 추가

- src/main/java/store/ckin/api/book/repository/impl/BookRepositoryImpl.java
- src/main/java/store/ckin/api/objectstorage/service/impl/ObjectStorageServiceImpl.java
> DB를 Full Scan하여 페이징을 적용하는 문제 해결, ObjectStorage에 사진 등록 시 토큰 재발급하던 문제 해결
> [REFACTOR] DB를 Full Scan 및 ObjectStorage 토큰 문제 해결

- src/main/java/store/ckin/api/book/entity/Book.java
- src/main/java/store/ckin/api/payment/facade/PaymentFacade.java
- src/main/java/store/ckin/api/sale/controller/SaleController.java
- src/main/java/store/ckin/api/sale/dto/response/SaleDetailResponseDto.java
- src/main/java/store/ckin/api/sale/facade/SaleFacade.java
- src/main/java/store/ckin/api/sale/service/SaleService.java
- src/main/java/store/ckin/api/sale/service/impl/SaleServiceImpl.java
- src/test/java/store/ckin/api/payment/facade/PaymentFacadeTest.java
- src/test/java/store/ckin/api/sale/service/impl/SaleServiceImplTest.java
#85
> [front PR](https://github.com/nhnacademy-be4-ckin/ckin-front/pull/155)과 동일합니다
비회원의 주문 조회로, 주문 번호(UUID)를 통해 완료된 주문의 정보와 결제 정보까지 조회
> [FEAT] 주문 - 비회원 주문 상세 조회

- src/main/java/store/ckin/api/book/repository/impl/BookRepositoryImpl.java
- src/main/java/store/ckin/api/objectstorage/service/impl/ObjectStorageServiceImpl.java
- src/main/resources/application.properties
> 
> 책 조회 시 중복으로 보이던 리스트 수정 및 파일 크기 조정 업로드
> [REFACTOR] 책 조회 시 중복으로 보이던 리스트 수정

- src/main/java/store/ckin/api/book/controller/BookController.java
- src/main/java/store/ckin/api/book/dto/response/BookMainPageResponseDto.java
- src/main/java/store/ckin/api/book/repository/BookRepositoryCustom.java
- src/main/java/store/ckin/api/book/repository/impl/BookRepositoryImpl.java
- src/main/java/store/ckin/api/book/service/BookService.java
- src/main/java/store/ckin/api/book/service/impl/BookServiceImpl.java
> [FEATURE] 메인페이지 책 조회 api

- src/main/java/store/ckin/api/address/domain/request/AddressAddRequestDto.java
- src/main/java/store/ckin/api/address/domain/request/AddressUpdateRequestDto.java
- src/main/java/store/ckin/api/address/domain/response/MemberAddressResponseDto.java
- src/main/java/store/ckin/api/address/entity/Address.java
- src/main/java/store/ckin/api/address/repository/impl/AddressRepositoryImpl.java
- src/main/java/store/ckin/api/address/service/impl/AddressServiceImpl.java
> [REFACTOR] Address : 우편 번호 컬럼 추가

- src/main/java/store/ckin/api/address/domain/response/MemberAddressResponseDto.java
- src/main/java/store/ckin/api/address/repository/impl/AddressRepositoryImpl.java
- src/main/java/store/ckin/api/address/service/impl/AddressServiceImpl.java
> [REFACOTR] 오류 수정

- src/main/java/store/ckin/api/member/controller/MemberController.java
- src/main/java/store/ckin/api/member/domain/request/MemberEmailOnlyRequestDto.java
- src/main/java/store/ckin/api/member/service/MemberService.java
- src/main/java/store/ckin/api/member/service/impl/MemberServiceImpl.java
> [FEAT] 회원가입 시 이메일 중복확인을 위한 API Method(checkDuplicateEmail)

- src/docs/asciidoc/delivery-policy.adoc
- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/packaging.adoc
- src/docs/asciidoc/payment.adoc
- src/docs/asciidoc/point-history.adoc
- src/docs/asciidoc/point-policy.adoc
- src/docs/asciidoc/sale.adoc
- src/main/java/store/ckin/api/packaging/dto/request/PackagingUpdateRequestDto.java
- src/main/java/store/ckin/api/payment/controller/PaymentController.java
- src/main/java/store/ckin/api/payment/dto/request/PaymentRequestDto.java
- src/main/java/store/ckin/api/sale/dto/request/SaleCreateRequestDto.java
- src/main/java/store/ckin/api/sale/facade/SaleFacade.java
- src/test/java/store/ckin/api/deliverypolicy/controller/DeliveryPolicyControllerTest.java
- src/test/java/store/ckin/api/packaging/controller/PackagingControllerTest.java
- src/test/java/store/ckin/api/payment/controller/PaymentControllerTest.java
- src/test/java/store/ckin/api/pointhistory/controller/PointHistoryControllerTest.java
- src/test/java/store/ckin/api/pointpolicy/controller/PointPolicyControllerTest.java
- src/test/java/store/ckin/api/sale/controller/SaleControllerTest.java
- src/test/java/store/ckin/api/sale/facade/SaleFacadeTest.java
- src/test/java/store/ckin/api/sale/service/impl/SaleServiceImplTest.java
- src/test/java/store/ckin/api/tag/controller/TagControllerTest.java
- 주문 테스트 코드 작성
- 담당한 파트 (주문, 포인트 정책, 포인트 내역, 포장 정책, 배송비 정책, 결제) Rest Docs 작성
> [FEAT] 주문 테스트 코드 & 담당 RestDocs

- src/main/java/store/ckin/api/book/entity/Book.java
- src/main/java/store/ckin/api/booksale/service/impl/BookSaleServiceImpl.java
주문이 완료 되었을 때 주문한 도서 수량이 감소하는 로직을 추가하였습니다.
> [REFACTOR] 주문 - 도서 수량 감소 추가

- src/test/java/store/ckin/api/member/repository/MemberRepositoryTest.java
> [TEST] MemberRepositoryTest

- src/main/java/store/ckin/api/book/controller/BookController.java
- src/main/java/store/ckin/api/book/dto/response/BookResponseDto.java
- src/main/java/store/ckin/api/book/repository/BookRepositoryCustom.java
- src/main/java/store/ckin/api/book/repository/impl/BookRepositoryImpl.java
- src/main/java/store/ckin/api/book/service/BookService.java
- src/main/java/store/ckin/api/book/service/impl/BookServiceImpl.java
- src/main/java/store/ckin/api/review/controller/ReviewController.java
- src/test/java/store/ckin/api/review/controller/ReviewControllerTest.java
> [REFACTOR] 도서 페이지

- src/docs/asciidoc/book.adoc
- src/main/java/store/ckin/api/author/entity/Author.java
- src/main/java/store/ckin/api/author/service/impl/AuthorServiceImpl.java
- src/main/java/store/ckin/api/book/controller/BookController.java
- src/main/java/store/ckin/api/book/service/impl/BookServiceImpl.java
- src/main/java/store/ckin/api/category/controller/CategoryController.java
- src/main/java/store/ckin/api/category/dto/response/CategoryNameResponseDto.java
- src/main/java/store/ckin/api/category/repository/CategoryRepository.java
- src/main/java/store/ckin/api/category/service/impl/CategoryServiceImpl.java
- src/main/java/store/ckin/api/file/entity/File.java
- src/main/java/store/ckin/api/review/controller/ReviewController.java
- src/main/java/store/ckin/api/review/dto/request/ReviewUpdateRequestDto.java
- src/main/java/store/ckin/api/review/entity/Review.java
- src/main/java/store/ckin/api/review/exception/UnauthorizedReviewAccessException.java
- src/main/java/store/ckin/api/review/facade/ReviewFacade.java
- src/main/java/store/ckin/api/review/service/ReviewService.java
- src/main/java/store/ckin/api/review/service/impl/ReviewServiceImpl.java
- src/test/java/store/ckin/api/author/service/impl/AuthorServiceImplTest.java
- src/test/java/store/ckin/api/book/controller/BookControllerTest.java
- src/test/java/store/ckin/api/book/repository/impl/BookRepositoryImplTest.java
- src/test/java/store/ckin/api/book/service/impl/BookServiceImplTest.java
- src/test/java/store/ckin/api/file/repository/FileRepositoryImplTest.java
- src/test/java/store/ckin/api/objectstorage/service/impl/ObjectStorageServiceImplTest.java
- src/test/java/store/ckin/api/review/repository/impl/ReviewRepositoryTest.java
- src/test/java/store/ckin/api/review/service/ReviewServiceTest.java
> ex)
> book review 테스트 코드 작성 및 Rest docs 작성
> [TEST] book review 테스트 코드 작성 및 Rest docs 작성

- src/test/java/store/ckin/api/tag/controller/TagControllerTest.java
> [FIX] Test Code Code smell 제거

- src/main/java/store/ckin/api/member/controller/MemberController.java
- src/main/java/store/ckin/api/member/domain/request/MemberPasswordRequestDto.java
- src/main/java/store/ckin/api/member/domain/request/MemberUpdateRequestDto.java
- src/main/java/store/ckin/api/member/domain/response/MemberDetailInfoResponseDto.java
- src/main/java/store/ckin/api/member/domain/response/MemberMyPageResponseDto.java
- src/main/java/store/ckin/api/member/domain/response/MemberPasswordResponseDto.java
- src/main/java/store/ckin/api/member/entity/Member.java
- src/main/java/store/ckin/api/member/exception/MemberPasswordCannotChangeException.java
- src/main/java/store/ckin/api/member/repository/MemberRepositoryCustom.java
- src/main/java/store/ckin/api/member/repository/impl/MemberRepositoryImpl.java
- src/main/java/store/ckin/api/member/service/MemberService.java
- src/main/java/store/ckin/api/member/service/impl/MemberServiceImpl.java
- src/test/java/store/ckin/api/member/repository/MemberRepositoryTest.java
- MemberMyPageResponseDto
- 비밀번호 변경 API
- 회원정보 수정 API
- 비밀번호 API API
- 회원정보 조회 API
>
> [FEAT] Member 관련

- src/main/java/store/ckin/api/category/controller/CategoryController.java
- src/main/java/store/ckin/api/category/dto/response/CategoryCacheResponseDto.java
- src/main/java/store/ckin/api/category/service/CategoryService.java
- src/main/java/store/ckin/api/category/service/impl/CategoryServiceImpl.java
> 카테고리 캐싱기능 추가를 위한 dto 및 컨트롤러 구현했습니다.
> [FEATURE] 카테고리 캐싱기능 추가

- src/docs/asciidoc/address.adoc
- src/docs/asciidoc/grade.adoc
- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/member.adoc
- src/test/java/store/ckin/api/address/controller/AddressControllerTest.java
- src/test/java/store/ckin/api/member/controller/MemberControllerTest.java
> [FEAT] REST Docs

- src/main/java/store/ckin/api/cart/controller/CartController.java
- src/main/java/store/ckin/api/cart/dto/CartCreateRequestDto.java
- src/main/java/store/ckin/api/cart/dto/CartIdResponseDto.java
- src/main/java/store/ckin/api/cart/entity/Cart.java
- src/main/java/store/ckin/api/cart/exception/CartAlreadyExistException.java
- src/main/java/store/ckin/api/cart/exception/CartNotFoundException.java
- src/main/java/store/ckin/api/cart/repository/CartRepository.java
- src/main/java/store/ckin/api/cart/repository/CartRepositoryCustom.java
- src/main/java/store/ckin/api/cart/repository/CartRepositoryImpl.java
- src/main/java/store/ckin/api/cart/service/CartService.java
- src/main/java/store/ckin/api/cart/service/CartServiceImpl.java
#120 
- 장바구니(Cart) 테이블 변경 (memberId(PK), cartId)
- 테이블 조회 및 저장 로직 추가
> [FEAT] 장바구니 DB 변경, 회원 별 장바구니 적용
